version: '3'
services: 
  nginx-proxy:
      image: jwilder/nginx-proxy
      container_name: "magenv-proxy"
      ports:
        - "80:80"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
  magento:
    image: nginx:latest
    container_name: "magenv-magento"
    volumes:
        - ./magento:/code/magento
        - ./env/magento.conf:/etc/nginx/conf.d/magento.conf
    environment:
      - VIRTUAL_HOST=seuteste.sualoja
    links:
        - php
        - db
  php:
    build: env/php/
    container_name: "magenv-php"
    volumes:
    - ./magento:/code/magento
    links:
      - db
  db:
    image: mysql/mysql-server:latest
    container_name: "magenv-db"
    ports:
      - "3306:3306"

    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=Mudar123
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento